version: '3'
services:
    db:
        image: 'mongo:4.0'
        restart: always
        env_file:
            - envs/db.env
        volumes:
            - 'data_db:/data/db'
            - 'data_configdb:/data/configdb'
            - 'var_log:/var/log'
    core-cwmp:
        image: mxhob1/genieacs:cwmp
        depends_on:
            - db
        env_file:
            - envs/core.env
        volumes:
            - 'var_log:/var/log'
    core-nbi:
        image: mxhob1/genieacs:nbi
        depends_on:
            - core-cwmp
        env_file:
            - envs/core.env
        volumes:
            - 'var_log:/var/log'
    core-fs:
        image: mxhob1/genieacs:fs
        depends_on:
            - core-cwmp
        env_file:
            - envs/core.env
        volumes:
            - 'var_log:/var/log'
    core-ui:
        image: mxhob1/genieacs:ui
        depends_on:
            - core-cwmp
        env_file:
            - envs/core.env
        volumes:
            - 'var_log:/var/log'
volumes:
    data_db:
        driver: local
    data_configdb:
        driver: local
    var_log:
        driver: local
